dist: trusty
sudo: false

language: bash

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.rvm

script:
  - bash -xe < ./assets/build/ci.sh

branches:
  only:
    - master
    - CI

addons:
  apt:
    packages:
      - g++-mingw-w64
      - gcc-4.8-multilib-arm-linux-gnueabihf
      - gcc-arm-linux-gnueabihf
      - lftp
      - libc6-dev-armhf-cross
      - p7zip-full
